// Module included in the following assemblies:
//
// Baking and decorating a chocolate birthday cake

[id='preparing-your-tools_{context}']

= Preparing your tools for baking a chocolate birthday cake

Prepare your tools before you mix your batter. The batter needs to start baking soon after it's mixed, so you want everything to be ready ahead of time. 

[discrete]
== Prerequisites

* A bulleted list of conditions that must be satisfied before the user starts following this assembly.
* You can also link to other modules or assemblies the user must follow before starting this assembly.
* Delete the section title and bullets if the assembly has no prerequisites.

[discrete]
== Procedure

. Preheat the oven to 350 degrees F. This will take some time, so be sure to do it first.

. Cut out a circle of baking parchment the size of the bottom of the pan. To get the size right, set the pan on your baking parchment and draw the outline of the pan on the paper in pen. Then remove the pan and cut just inside the line. The circle of paper should fit in the bottom of the pan. 

[discrete]
== Additional Resources

* resource 1
* resource 2
