// Module included in the following assemblies:
//
// Baking and decorating a chocolate birthday cake

[id='bake-and-cool_{context}']

= Baking and cooling your layers

Bake and cool your cake layers

[discrete]
== Prerequisites

* Make sure your oven is fully preheated to 350 degrees F.
* Ingredients mixed and poured into pans.

[discrete]
== Procedure

. Put the pans in the preheated oven.

. After 20 minutes, look at the layers - if they look more like cakes than like batter, test doneness with a toothpick

. You will know a layer is done when a toothpick inserted into the center comes out clean

. As soon as a layer is done, remove it from the oven and place it on a cooling rack

. Repeat until all layers are cool. Turn the oven off.

. When a layer has cooled about ten minutes, run a knife around the edge of the pan. Place the cooling rack on top of the pan. The layer should fall out as you remove the pan. 

. Allow all layers to cool completely - you don't want the layers to be steaming when you put them together.
